version: '3.1'

services:
  php:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: restful-app
    ports:
      - 81:80
    volumes:
      - ./:/var/www/html/
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    container_name: restful-db
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
